### ISSUE TITLE
LoggerAwareInterface not found

### ISSUE THREAD

**Issue by aw73** [mediamonks/crawler#1]
When I installed and test the basic.php example I get this error

Fatal error: Interface 'Psr\Log\LoggerAwareInterface' not found in /vendor/mediamonks/crawler/src/Crawler.php on line 14

**Comment by slootjes** [comment]
This can be solved by requiring the "psr/log" package with composer "composer require psr/log". I will add this to the required packages.

**Comment by slootjes** [comment]
Should be solved in v1.0.1
